export const IMacImgColors = [
    {
        color:'green',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_green__bjxhwofb06b6_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_green__eb8qbnemmre6_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_green__buxxfjccqjzm_large.jpg'
        ]
    },
    {
        color:'yellow',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_yellow__f4a0s12fqj2a_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_yellow__cja2t2hwgcty_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_yellow__fmx5q8ntpj6m_large.jpg'
        ]
    },
    {
        color:'orange',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_orange__ekvz6n3e4u6a_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_orange__b5i6x9xifhua_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_orange__z9azngpmckyq_large.jpg'
        ]
    },
    {
        color:'red',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_pink__ci9ldbch42fm_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_pink__ewotg63rfmie_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_pink__f9bmifakmlm6_large.jpg'
        ]
    },
    {
        color:'purple',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_purple__e7cp0tpdh4ya_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_purple__bxvrajaaheeu_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_purple__f81x87oa92aa_large.jpg'
        ]
    },
    {
        color:'blue',
        imgs:
        [
            'https://www.apple.com/v/imac-24/h/images/overview/color_side_blue__db9cbvh5i9g2_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_front_blue__x3psx2ttezmi_large.jpg',
            'https://www.apple.com/v/imac-24/h/images/overview/color_back_blue__drupb0dshcmu_large.jpg'
        ]
    },
]